//Organiational
export const searchRegion = '/org/searchRegion'
export const searchOrgDistChannel = '/org/searchChannel'
export const searchCompany = '/org/searchCompany'
export const searchDivision = '/org/searchDivision'
export const searchProductConversion = '/org/searchProductConversion'
export const searchSaleGroup = '/org/searchSaleGroup'
export const searchSaleOffice = '/org/searchOffice'
export const searchSaleOrg = '/org/searchOrg'
export const searchTerritory = '/org/searchTerritory'
export const updateManagerSaleGroup = '/org/updrSaleGroupByManagerEmpId'
export const searchForPlant = '/org/searchPlantShip'
export const searchForShippingPoint = '/org/searchPlantShip'
export const searchBusinessUnit = '/org/searchBusinessUnit'
export const addBusinessUnit = '/org/addBusinessUnit'
export const updateBusinessUnit = '/org/updBusinessUnit'
export const deleteBusinessUnit = '/org/cancelBusinessUnit'
export const mapBU = '/org/mapBU'
export const searchEmpByTerritoryId = '/org/searchEmpByTerritoryId'
export const searchEmpForMapSaleTerritory = '/org/searchEmpForMapSaleTerritory'

export const searchSaleGroupForMapSaleTerritory = '/org/searchSaleGroupForMapSaleTerritory'
export const updTerritorySaleGroup = '/org/updTerritorySaleGroup'

export const addTerritory = '/org/addTerritory'
export const updTerritory = '/org/updTerritory'
export const cancelTerritory = '/org/cancelTerritory'
export const updTerritoryByManagerEmpId = '/org/updTerritoryByManagerEmpId'
export const addSaleTerritory = '/org/addSaleTerritory'
export const delSaleTerritory = '/org/delSaleTerritory'
export const searchSaleArea = '/org/searchSaleArea'
export const searchPlantByCompanyCode = '/searchPlantByCompanyCode'
export const searchShippingPointByPlantCode = '/searchShippingPointByPlantCode'
// Master
export const addRegion = '/org/addRegion'
export const updRegion = '/org/updRegion'
export const cancelRegioin = '/org/cancelRegioin'
export const searchProvince = '/org/searchProvince'
export const searchDistrict = '/org/searchDistrict'
export const searchMsSubDistrict = '/org/searchMsSubDistrict'
export const updDistrictByProvinceCode = '/org/updDistrictByProvinceCode'
export const searchSubDistrict = '/org/searchSubDistrict'
export const updSubDistrictByDistrictCode = '/org/updSubDistrictByDistrictCode'
export const updProvince = '/org/updProvince'
export const delSubDistrictSomById = 'org/delSubDistrictSomById'

export const updateReportProductConversion = '/org/updateReportProductConversion'

//Visit Plan
export const searchTemplateQuestion = '/org/searchTemplateQuestion'
export const addTemplateQuestion = '/org/addTemplateQuestion'
export const updTemplateQuestion = '/org/updTemplateQuestion'
export const deleteQuestion = '/org/cancelTemplateQuestion'
export const searchBrand = '/org/searchBrand'
export const addBrand = '/org/addBrand'
export const updBrand = '/org/updBrand'
export const cancelBrand = '/org/cancelBrand'
export const searchLoc = '/org/searchLoc'
export const addLoc = '/org/addLoc'
export const updLoc = '/org/updLoc'
export const cancelLoc = '/org/cancelLoc'
export const searchTemplateCate = '/org/searchTemplateCate'
export const addTemplateCate = '/org/addTemplateCate'
export const updTemplateCate = '/org/updTemplateCate'
export const cancelTemplateCate = '/org/cancelTemplateCate'

export const searchLocType = '/org/searchLocType'
export const addLocType = '/org/addLocType'
export const updLocType = '/org/updLocType'
export const cancelLocType = '/org/cancelLocType'

export const searchBrandCate = '/org/searchBrandCate'
export const addBrandCate = '/org/addBrandCate'
export const updBrandCate = '/org/updBrandCate'
export const cancelBrandCate = '/org/cancelBrandCate'

export const searchServiceType = '/org/searchServiceType'
export const addServiceType = '/org/addServiceType'
export const updServiceType = '/org/updServiceType'
export const cancelServiceType = '/org/cancelServiceType'

export const searchBank = '/org/searchBank'
export const addBank = '/org/addBank'
export const updBank = '/org/updBank'
export const cancelBank = '/org/cancelBank'

export const searchAttachCate = '/org/searchAttachCate'
export const addAttachCate = '/org/addAttachCate'
export const updAttachCate = '/org/updAttachCate'
export const cancelAttachCate = '/org/cancelAttachCate'

export const searchGasoline = '/org/searchGasoline'
export const addGasoline = '/org/addGasoline'
export const updGasoline = '/org/updGasoline'
export const cancelGasoline = '/org/cancelGasoline'

export const searchPlanReasonNotVisit = '/org/searchPlanReasonNotVisit'
export const addPlanReasonNotVisit = '/org/addPlanReasonNotVisit'
export const updPlanReasonNotVisit = '/org/updPlanReasonNotVisit'
export const cancelPlanReasonNotVisit = '/org/cancelPlanReasonNotVisit'

export const searchTemplateAppForm = '/org/searchTemplateAppForm'
export const addTemplateAppForm = '/org/addTemplateAppForm'
export const updTemplateAppForm = '/org/updTemplateAppForm'
export const cancelTemplateAppForm = '/org/cancelTemplateAppForm'
export const searchTemplateAppQuestionById = '/org/searchTemplateAppQuestionById'
export const addTemplateAppQuestion = '/org/addTemplateAppQuestion'
export const updTemplateAppQuestion = '/org/updTemplateAppQuestion'
export const cancelTemplateAppQuestion = '/org/cancelTemplateAppQuestion'

export const searchProduct = '/org/searchProduct'
export const searchGasolineByCust = '/org/searchGasolineByCust'

export const searchCustomer = '/org/searchCustomer'
export const addMeter = '/org/addMeter'
export const updMeter = '/org/updMeter'
export const cancelMeter = '/org/cancelMeter'

export const updBusinessUnitSaleArea = '/org/updBusinessUnitSaleArea'

export const searchTemplateSaForm = '/org/searchTemplateSaForm'
export const addTemplateSaForm = '/org/addTemplateSaForm'
export const updTemplateSaForm = '/org/updTemplateSaForm'
export const cancelTemplateSaForm = '/org/cancelTemplateSaForm'
export const searchTemplateSaFormById = '/org/searchTemplateSaFormById'
export const addTemplateSaTitle = '/org/addTemplateSaTitle'
export const delTemplateSaTitle = '/org/delTemplateSaTitle'
export const searchTemplateStockCard = '/org/searchTemplateStockCard'
export const addTemplateStockCard = '/org/addTemplateStockCard'
export const updTemplateStockCard = '/org/updTemplateStockCard'
export const cancelTemplateStockCard = '/org/cancelTemplateStockCard'
export const searchTemplateByStockCardId = '/org/searchTemplateByStockCardId'
export const addTemplateStockProduct = '/org/addTemplateStockProduct'
export const cancelTemplateStockProduct = '/org/cancelTemplateStockProduct'
export const delTemplateStockProduct = '/org/delTemplateStockProduct'

//Admin
export const getConfigLov = '/org/getConfigLov'
export const searchAdmEmployee = '/adm/searchAdmEmp'
export const deleteSaleGroupWithOutSaleRep = '/adm/cancelSaleGroupByEmpId'
export const updateSaleGroupToSaleRep = '/adm/updAdmEmpBySaleGroup'
export const searchAdmGroup = '/adm/searchAdmGroup'
export const searchAdmEmployeeAdmGroup = '/adm/searchAdmEmpForMapRole'
export const getEmpSupvisor = '/adm/searchAdmEmpRoleSupvisor'
export const getAdmGroup = '/adm/searchAdmGroup'
export const mapRole = '/adm/mapRoleWithEmp'
export const searchAdmEmpRoleManager = '/adm/searchAdmEmpRoleManager'
export const updateApproverToSaleRep = '/adm/updAdmEmpByApprover'
export const addAdmGroup = '/adm/addAdmGroup'
export const updateAdmGroup = '/adm/updAdmGroup'
export const deleteAdmGroup = '/adm/cancelAdmGroup'

export const searchAdmPermObject = '/searchAdmPermObject'
export const searchAdmGroupApp = '/searchAdmGroupApp'
export const addAdmGroupApp = '/addAdmGroupApp'
export const updAdmGroupApp = '/updAdmGroupApp'
export const cancelAdmGroupApp = '/cancelAdmGroupApp'
export const searchAdmGroupPerm = '/searchAdmGroupPerm'
export const updAdmGroupPerm = '/updAdmGroupPerm'

//Secure
export const login = '/secure/login'
export const logout = '/secure/logout'
export const getUserProfile = '/secure/getUserProfile'

//import file
export const importEmpToSaleGroup = '/importEmpToSaleGroup'