// Primary Menu
export const defaultTitle = 'PTG-Sale'
//CommonLabel
export const yes = 'ใช่'
export const no = 'ไม่ใช่'
export const search = 'Search'
export const confirm = 'Confirm'
export const cancle = 'Cancel'
export const add = 'Add'
export const edit = 'Edit'
export const go = 'Go'
export const save = 'Save'
export const clear = 'Clear'
export const close = 'Close'
export const print = "Print"
export const select = "Select"
export const selectSaleArea = "Select Sale Area"
export const ok = 'OK'
export const del = ''
export const numOrder = 'ลำดับ'
export const move = 'Move'
export const create = 'Create'
export const createBy = 'โดย'
export const lastUpdate = 'Last Update'
export const APIError = 'เกิดความผิดพลาด'
export const pleaseSelect = 'กรุณาเลือก '
export const pleaseFill = 'กรุณาระบุ '
export const selectNoData = 'ไม่พบข้อมูล'
export const uploadFile = 'Upload File'
export const deleteFull = 'Delete'
export const wrongEmail = ' ไม่ถูกต้อง'
export const time = "เวลา"
export const day = "วัน"
export const to = "วันที่สิ้นสุด"
export const from = "วันที่เริ่มต้น"
export const back = "Back"
export const today = "Today"
export const view = "View"
export const accept = "Accept"
export const date = "Date"
export const send = "Send"
export const reject = "Reject"
export const approve = "Approve"
export const exportMsg = "Export"
export const total = "Total"
export const status = "Status"

//CardTableLabel
export const cardTableShowing = 'แสดง'
export const cardTableTasks = 'รายการ'
export const cardTablePage = 'หน้า'
export const cardTableOf = 'ของ'
export const cardTableFilter = 'ตัวกรอง'

//TableLabel
export const tableShowSearchResult = 'แสดงผลการค้นหา'
export const tableShowing = 'แสดง'
export const tableTo = 'ถึง'
export const tableOf = 'ของ'
export const tableEntries = 'รายการ'
export const tableGotoPage = 'ไปที่หน้า'
export const tableNoData = 'ไม่พบข้อมูล'

//AlertMsg
export const saveSuccess = 'บันทึกข้อมูลสำเร็จ'
export const addSuccess = 'เพิ่มข้อมูลสำเร็จ'
export const editSuccess = 'แก้ไขข้อมูลสำเร็จ'
export const deleteSuccess = 'ลบข้อมูลสำเร็จ'
export const confirmDelete = 'ต้องการลบข้อมูลนี้ใช่หรือไม่'
export const confirmLogout = 'ต้องการออกจากระบบใช่หรือไม่'
export const atLestOne = 'กรุณาระบุข้อมูลในการค้นหา'
export const visitHourDup = 'ช่วงเวลาที่เลือกซ้ำกับช่วงเวลาดังต่อไปนี้'
export const timeRangWrong = 'กรุณาเลือกช่วงเวลาให้ถูกต้อง'
export const atLestOneDay = 'กรุณาเลือกวันอย่างน้อย 1 วัน'
export const cloneSuccess = 'Clone ข้อมูลสำเร็จ'
export const planTripTaskMin1 = 'ต้องมี Task อย่างน้อย 1 Task'
export const planTripProspectMin1 = 'ต้องมี Prospect/Customer อย่างน้อย 1 รายการ'
export const cantNotfindRoute = 'ไม่สามารถค้นหาเส้นทางได้'
export const taskListEmpty = 'ไม่สามารถบันทึกได้เนื่องจาก Prospect/Customer ดังต่อไปนี้ยังไม่มี Task งาน'
export const pleaseSelectSaleArea = 'กรุณาเลือก Sale Area ก่อน'
export const pleaseInputAtLestOneField = "กรุณาเลือกข้อมูลในการค้นหาอย่างน้อย 1 ข้อมูล"
export const dupProduct = "ไม่สามารถเพิ่มได้เนื่องจาก มี Product ที่มี Unit นี้อยู่แล้ว"
export const pleseFillAllReqField = "กรุณาระบุข้อมูลบังคับกรอกให้ครบถ้วน"
export const cantDelete = 'ไม่สามารถลบข้อมูลได้'
export const apiError = "เกิดความผิดพลาด กรุณาทำรายการใหม่อีก"
export const latOrLongWorng = 'Latitude/Longitude ไม่ถูกต้อง กรุณาระบุข้อมูลใหม่'
export const enterBothLatAndLong = 'กรุณาระบุข้อมูลทั้ง Latitude และ Longitude'


//Label

export const notifications = "Notifications"
export const preTitle = "Good morning,"
export const company = 'Company'
export const companyCode = 'Company Code'
export const companyName = 'Company Name'
export const vatRegistration = 'VAT Registration No.'
export const salesOrgCode = 'Sales Organization Code'
export const salesOrgName = 'Sales Organization Name'
export const salesOrgComName = 'Company Name'
export const salesOrgCurrency = 'Statistics currency'
export const distributionChannelCode = 'Distribution Channel Code'
export const distributionChannelName = 'Distribution Channel Name'
export const divisionCode = 'Division Code'
export const divisionName = 'Division Name'
export const salesOfficeCode = 'Sales Office Code'
export const saleOfficeName = 'Sale Office Name'
export const salesGroupCode = 'Sales Group Code'
export const salesGroupName = 'Sales Group Name'
export const salesGroupLeader = 'Sales Group Leader'
export const salesGroupEdit = 'Edit'
export const employeeCode = 'Employee Code'
export const employeeName = 'Employee Name'
export const headerListEmployee = 'รายการ Employee'
export const employeeHaveGroup = 'พนักงานดังต่อไปนี้มีกลุ่มอยู่แล้วต้องการเพิ่มลงกลุ่มหรือไม่'
export const saleRepJobTitle = 'Job Title'
export const saleRepRoleOnSom = 'Role on SOM'
export const saleRepBuName = 'Bu Name'
export const headerDialogSaleRep = 'Role on SOM'
export const approverCode = 'Approver Code'
export const approverName = 'Approver Name'
export const headerDialogApprover = 'Approver'
export const roleCode = 'Role Code'
export const roleName = 'Role Name'
export const headerDialogRoleOnSOM = 'Role'
export const saleAreaSaleOrgCode = 'Sales Organization Code'
export const saleAreaSaleOrgName = 'Sales Organization Name'
export const saleAreaChannelCode = 'Distribution Channel Code'
export const saleAreaChannelName = 'Distribution Channel Name'
export const saleAreaDivisionCame = 'Division Code'
export const saleAreaDivisionName = 'Division Name'
export const saleAreaBuCode = 'Business Area Code'
export const saleAreaBuName = 'Business Area Name'
export const businessUnitCode = 'BU Code'
export const businessUnitName = 'BU Name'
export const headerDialogBusinessUnit = 'Business Unit'
export const plantCode = 'Plant Code'
export const plantName = 'Plant Name'
export const plantCity = 'City'
export const plantCustomer = 'Customer no. - plant'
export const plantVendor = 'Vendor number plant'
export const plantFactory = 'Factory calendar'
export const plantPurch = 'Purch. Organization'
export const plantBusiness = 'Business Place'
export const plantShipping = 'Shipping Point Name'
export const shippingPointCode = 'Shipping Point Code'
export const shippingPointName = 'Shipping Point Name'
export const shippingPlantName = 'Plant Name'
export const territoryCode = 'Territory Code'
export const territoryName = 'Territory Name'
export const territoryLeader = 'Territory Leader'
export const manageSale = 'Manage Sale Representative'
export const headerDialogTerritory = 'Territory'
export const territorySaleGroupCode = 'Sales Group Code'
export const territorySaleGroupName = 'Sales Group Name'
export const territorySaleRepCode = 'Sales Representative Code'
export const territorySaleRepName = 'Sales Representative Name'
export const headerListSaleRep = 'รายการ Sales Representative'
export const headerDialogRegion = 'Region'
export const provinceCode = 'รหัสจังหวัด'
export const districtCode = 'รหัสอำเภอ'
export const districtName = 'ชื่ออำเภอ'
export const subDistrictCode = 'รหัสตำบล'
export const subDistrictName = 'ชื่อตำบล'
export const brandCode = 'รหัส'
export const locationCode = 'รหัส'
export const empCodeForLogin = 'ชื่อผู้ใช้งาน'
export const password = 'รหัสผ่าน'
export const login = 'Login'
export const questionCode = 'รหัส'
export const question = 'Question (คำถาม)'
export const questionName = 'Question (คำถาม)'
export const questionCategory = 'ประเภทคำถาม'
export const publicFlag = 'เผยแพร่'
export const answer = 'คำตอบ'
export const templateCode = 'รหัส'
export const template = 'Template'
export const templateName = 'Template'
export const templateCategory = 'Template Category (ประเภท Template)'
export const headerDialogTemplateCate = 'Template Category (ประเภท Template)'
export const questionList = 'รายการคำถาม'
export const questionRequired = 'Required'
export const prerequisite = 'Prerequisite'
export const dialogCheckProvince = 'จังหวัดดังต่อไปนี้มีกลุ่มอยู่แล้วต้องการเพิ่มลงกลุ่มหรือไม่'
export const headerListProvince = 'รายการ Province'
export const provinceId = 'รหัสจังหวัด'
export const provinceName = 'ชื่อจังหวัด'
export const regionCode = 'รหัสภูมิภาค'
export const regionName = 'ชื่อภูมิภาค'
export const region = 'ภูมิภาค'
export const regionId = 'รหัสภูมิภาค'
export const code = 'รหัส'
export const mapping = 'Mapping'
export const provinceInRegion = 'Mapping ภูมิภาคกับจังหวัด'
export const location = 'ชื่อสถานที่'
export const locationFull = 'Location (สถานที่)'
export const locationType = 'ประเภทสถานที่'
export const locationName = 'ชื่อสถานที่'
export const locationNameEn = 'Location Name'
export const locationTypeCode = 'รหัส'
export const locationTypelabel = 'Location Type (ประเภทสถานที่)'
export const headerDialogLocType = 'Location Type (ประเภทสถานที่)'
export const categoriesCode = 'รหัส'
export const categoriesName = 'Category (ชนิด)'
export const headerDialogCategories = 'Category (ชนิด)'
export const serviceCode = 'รหัส'
export const serviceType = 'Service (ประเภทบริการ)'
export const headerDialogService = 'Service (ประเภทบริการ)'
export const bankCode = 'รหัส'
export const bankName = 'Bank (ธนาคารที่ใกล้เคียง)'
export const headerDialogBank = 'Bank (ธนาคารที่ใกล้เคียง)'
export const attachCateCode = 'รหัส'
export const attachCateType = 'Attachment Category (ประเภทของไฟล์แนบ)'
export const gasId = 'รหัส'
export const gasName = 'Product Category (ประเภทผลิตภัณฑ์)'
export const reasonCode = 'รหัส'
export const reasonName = 'Reason Not Visit (เหตุผลไม่เข้าเยี่ยม)'
export const productId = 'ลำดับ'
export const productCode = 'รหัส'
export const productName = 'Product (สินค้า)'
export const division = 'Division Name'
export const custCode = 'รหัสลูกค้า'
export const custName = 'ชื่อลูกค้า'
export const productType = 'ประเภทผลิตภัณฑ์'
export const dispenser = 'ตู้น้ำมัน'
export const nozzle = 'มือจ่ายที่'
export const qrCode = 'QR'
export const qrMaster = 'QR Master'
export const templateForSaId = 'รหัส'
export const templateForSaName = 'ชื่อโครงการ'
export const templateForSaCode = 'รหัสโครงการ'
export const templateForSa = 'โครงการ'
export const templateForSaTitleDialog = 'ข้อมูล'
export const masterField = 'Master Field'
export const titleField = 'Title Field'
export const type = 'ประเภท'
export const data = 'Data'
export const templateStockCardName = 'Template Stock Card Name'
export const templateStockCardCode = 'Template Stock Card Code'
export const headerDialogTemplateStockCard = 'Template Stock Card'
export const productList = 'รายการสินค้า'
export const prospect = 'Prospect'
export const createProspect = 'Create Prospect'
export const myProspect = 'My Prospect'
export const reccomendBU = 'Reccomend BU'
export const inTerritory = 'In Territory'
export const prospectInfo = 'Prospect Info'
export const newAccount = 'New Account'
export const brand = 'แบรนด์'
export const taxNumberOrIDCard = 'Tax Number/ID Card'
export const vatNumber = 'Vat Number'
export const enterBothVatNumber = 'กรุณาระบุข้อมูล'
export const enterVatNumberLessThen13 = 'กรุณาระบุข้อมูลให้ครบถ้วน'
export const prospectGroupRef = 'Prospect Group Rep.'
export const name = 'ชื่อ'
export const lastName = 'นามสกุล'
export const address = 'Address'
export const addressNo = 'เลขที่บ้าน'
export const moo = 'หมู่ที่'
export const soi = 'ตรอก/ซอย'
export const road = 'ถนน'
export const telNo = 'เบอร์โทรศัพท์'
export const mobileNo = 'เบอร์โทรศัพท์มือถือ'
export const faxNo = 'เบอร์แฟกซ์'
export const email = 'อีเมล'
export const latitude = 'Latitude'
export const longitude = 'Longitude'
export const coordinates = 'Latitude/Longitude'
export const province = 'จังหวัด'
export const district = 'อำเภอ/เขต'
export const subDistrict = 'ตำบล/แขวง'
export const postCode = 'รหัสไปรษณีย์'
export const remark = 'หมายเหตุ'
export const remind = 'Remind'
export const contactInfo = 'Contact Info'
export const labelSA = 'SA'
export const labelFeed = 'Feed'
export const labelSalesTerritory = 'Sales Territory'
export const labelAddress = 'Address'
export const labelContact = 'Contact'
export const labelSaleOrder = 'Sales Order'
export const labelAttachments = 'Attachments'
export const labelVisitingHours = 'Visiting Hours'
export const labelSurveyResults = 'Survey Results'
export const labelRecommendBU = 'Recommend BU'
export const labelTemplateForSA = 'Template For SA'
export const labelMeter = 'จดมิเตอร์'
export const labelStockCount = 'Stock Count'
export const labelSaleData = 'Sales Data'
export const labelDBD = 'DBD'
export const labelAccountTeam = 'Account Team'
export const labelBasic = 'Basic'
export const territory = 'Territory'

export const siteType = 'ประเภท Site'
export const service = 'ประเภทบริการ'
export const accountStatus = 'สถานะบัญชี'
export const stationName = 'ชื่อสถานี'
export const gasStationStatus = 'สถานะปั๊มน้ำมัน'
export const reasonForCancel = 'เหตุผลการยกเลิก'
export const typeProduct = 'ประเภทผลิตภัณฑ์'
export const typeProductOther = 'ประเภทผลิตภัณฑ์ (อื่นๆ)'
export const areaRai = 'พื้นที่ (ไร่)'
export const areaNgan = 'พื้นที่ (งาน)'
export const areaSquareWah = 'พื้นที่ (ตารางวา)'
export const widthMeters = 'หน้ากว้าง (เมตร)'
export const shopInStation = 'ร้านค้าเช่าภายในสถานีเช่า'
export const statusLicense = 'สถานะใบอนุญาต'
export const statusLicenseOther = 'สถานะใบอนุญาต (กรณีอื่นๆ)'
export const attentionCust = 'ความสนใจลูกค้า'
export const attentionCustOther = 'ความสนใจลูกค้า (กรณีอื่นๆ)'
export const salesMonthly = 'ยอดขายต่อเดือน (ลิตร) 3 เดือนล่าสุด'
export const dataSalesMonthly = "อ้างอิงยอดขาย 3 เดือนล่าสุด"
export const yearOperation = 'ปีที่เปิดดำเนินการ'
export const expDateLease = 'วันหมดสัญญาเช่า'
export const visitDate = 'วันที่เข้าเยี่ยม'
export const deedCode = 'เลขที่โฉนด'
export const landCode = 'เลขที่ดิน'
export const explore = 'หน้าสำรวจ'
export const deedType = 'ประเภทโฉนดที่ดิน'
export const isGasStation = 'เป็นปั๊มเช่า'
export const details = 'รายละเอียด'
export const contactDetail = 'รายละเอียด'
export const searchTerritories = 'Search Territories'
export const salesTterritories = 'Sales territories'
export const dedicatedSalesTerritories = 'Dedicated sales territories'
export const salesRep = 'Sales Rep'

export const allUpdate = 'All Update'
export const account = 'Account'
export const editTh = 'แก้ไข'
export const by = 'โดย'
export const role = "Role"
export const territoryId = "Territory Code"
export const allOrders = "All Orders"

export const contactName = 'Contact Name'
export const contactNumber = 'Contact Number'
export const prospectName = 'Prospect Name'
export const taxNumber = 'Tax Number'
export const pronice = 'Pronice'
export const codeDBD = 'Code DBD'
export const corporateType = 'Corporate Type'
export const juristicStatus = 'Juristic Status'
export const registerCapital = 'Register Capital'
export const totalIncome = 'Total Income'
export const profitLoss = 'Profit Loss'
export const totalAssets = 'Total Assets'
export const fleetCard = 'Fleet Card'
export const corporateCard = 'Corporate Card'
export const fuelUsed = 'ประมาณการการใช้น้ำมัน'
export const currentStation = 'สถานีบริการน้ำมันที่ใช้ปัจจุบัน'
export const payType = 'รูปแบบการชำระเงิน'
export const money = 'เงินสด'
export const credit = 'เงินเชื่อ'
export const fourWheelCar = 'รถ 4 ล้อ'
export const sixWheelCar = 'รถ 6 ล้อ'
export const eightWheelCar = 'รถ 8 ล้อ'
export const chainCar = 'รถพ่วง'
export const trailerCar = 'รถเทรลเลอร์'
export const containerTrailer = 'รถลากตู้คอนเทนเนอร์'
export const machinery = 'เครื่องจักร'
export const other = 'อื่นๆ'
export const withTank = 'มีแทงค์'
export const fuelStation = 'สถานีบริการน้ำมัน'
export const bothType = 'ทั้ง 2 รูปแบบ'
export const maintenanceCenter = 'ศูนย์ซ่อมบำรุง'
export const garage = 'อู่ทั่วไป'
export const companyMaintenanceDepartment = 'แผนกซ่อมบำรุงของบริษัท'
export const DBDStatus = 'Status'
export const recommender = 'ผู้แนะนำ'
export const saleMan = 'เจ้าหน้าที่ขาย'
export const afterSalesOfficer = 'เจ้าหน้าที่ดูแลหลังการขาย'
export const survey = "Survey"
export const customer = "Customer"
export const templateForSaInfo = "ข้อมูล"
export const templateForSaModalHeader = "Template For SA"
export const templateSurveyResultModalHeader = "Survey Result"
export const templateForSaTemplateName = "ชื่อ"
export const myCustomer = "My Customer"
export const salesOrder = "Sales Order"
export const description = "Description"
export const creationDate = "Creation Date"
export const pricingDate = "Pricing Date"
export const message = "Message"
export const divisionLabel = "Division"
export const saleOfficeLabel = "Sales Office"
export const saleGroupLabel = "Sales Group"
export const customerGroup = "Customer Group"
export const paymentTerms = "Payment Terms"
export const incoterms = "Incoterms"
export const stockCountLabel = "Stock Count"
export const numberLabel = "No."
export const productCodeLabel = "Product Code"
export const productNameLabel = "Product Name"
export const baseUnitLabel = "Base Unit"
export const qtyLabel = "Qty"
export const unitLabel = "Unit"
export const rentstation = "ปั๊มเช่า"
export const myRentstation = "ปั๊มเช่าของฉัน"
export const otherProspect = "Other Prospect"
export const myOtherProspect = "My Other Prospect"
export const dispenserNo = "ตู้น้ำมัน"
export const nozzleNo = "มือจ่ายที่"
export const meterProductName = "ประเภทผลิตภัณฑ์"
export const meterNo = "เลขมิเตอร์"
export const dateTime = "วันที่"
export const photoType = "ประเภทรูปภาพ"
export const clone = "Clone"
export const prospectData = "ข้อมูล Prospect"
export const customerData = "ข้อมูล Customer"
export const pumpData = "ข้อมูลปั๊มเช่า"
export const partyRole = "Party Role"
export const saleGroup = "Sale Group"
export const saleTerritory = "Sale Territory"
export const detailProspect = "Detail Prospect"

export const visitPlantHeader = "Sales Visit Plan"
export const createForMe = "Create for me"
export const createForOther = "Create for other"
export const plan = "Plan"
export const planStatus = "Status"
export const createDateTime = "วันที่สร้าง"
export const dateVisit = "วันที่เข้าเยี่ยม"

export const planTripName = "Plan Trip Name"
export const planTripLocation = "Location"
export const prospectAndCustomer = "Prospect/Customer"
export const createPlan = "Create Plan"
export const fillLocation = "ระบุสถานที่"
export const locationStart = "Start"
export const locationEnd = "Stop"
export const bestRoute = "Best Route"
export const visitPlanLocation = "Location"
export const specialTask = "Special Task"
export const taskTemplate = "Template"
export const taskTemplateName = "Template Name"
export const taskRequired = "Required"
export const shipTo = "Ship To"
export const billTo = "Bill To"
export const main = "Main"
export const priceList = 'Price List'
export const per = 'Per'

export const visitPlanRawData = "Visit Plan Raw Data"
export const visitPlanTransaction = "Visit Plan Summary KM by Employee"
export const materRawData = "Meter RawData"
export const materTransaction = "Meter Transaction"
export const stockCardRawData = "StockCard RawData"
export const prospectRawData = "Prospect RawData"
export const assignReport = "Assign Report"
export const saleOrderRawData = "Sale Order Raw Data"
export const visitPlanDaily = "Visit Plan Daily"
export const visitPlanMonthly = "Visit Plan Monthly"
export const visitPlanActual = "Visit Plan vs Actual"
export const prospectPerformancePerSaleRep = "Prospect Performance convert to customer (per sale rep)"
export const prospectPerformancePerGroup = "Prospect Performance convert to customer (per sale group)"
export const saleOrderByChannel = "Sale Order By Channel"
export const saleOrderByCompany = "Sale Order By Company"
export const imageInTemplate = "Image in Template"

export const reportStartDate = "วันที่เริ่มต้น"
export const reportEndDate = "วันที่สิ้นสุด"
export const reportSaleRepName = "Sale Rep Name"
export const reportSaleRepId = "Sale Rep ID"
export const reportVisitPlanId = "Visit Plan ID"
export const reportVisitPlanName = "Visit Plan Name"
export const reportVisitType = "Visit Type"
export const reportVisitDate = "Visit Date"
export const reportName = "Name"
export const reportNameCustomerAndProspect = "Customer/Prospect"
export const reportMileStart = "เลขไมล์ เริ่มต้น"
export const reportMileEnd = "เลขไมล์ สิ้นสุด"
export const reportTotalKMInput = "Total KM (by input)"
export const reportTotalKMSystem = "Total KM (by System)"
export const reportPlannedStartDate = "Planned start date/time"
export const reportPlannedEndDate = "Planned end date/time"
export const reportActualChekInDate = "Actual check in date/time"
export const reportActualChekOutDate = "Actual check out date/time"
export const reportPlanFailVisit = "เหตุผลในการไม่เข้าเยี่ยมตามแผน"
export const reportSaleId = "Sale Rep ID"

export const reportImage = "Image"



export const quatationNo = "Quotation"
export const createSaleOrder = "Create Sale Order"
export const saleOrganization = "Sale Organization"
export const distributionChannel = "Distribution Channel"
export const reguesteDeliveryDate = "Reguest Delivery Date"
export const saleRef = "Sale Rep"
export const contactPerson = "Contact Person"
export const PONumber = "PO Number"
export const saleOrder = "Sales Order"
export const saleOrderNo = "Sale Order No."
export const soNoSom = "SO No (SOM)"
export const soNoSap = "SO No (SAP)"
export const customerName = "Customer Name"
export const soDateTime = "SO Date Time"
export const simulateDateTime = "Simulate Date/Time"
export const documentType = "Document Type"
export const pricingDateTime = "Pricing Date/Time"
export const totalNetValue = "Total Net Value"
export const overview = "Overview"
export const product = "Product"
export const documentFlow = "Document Flow"
export const changes = "Changes"
export const orderReason = "Order Reason"
export const creditStatus = "Credit Status"
export const reasonForRejection = "Reason for Rejection"
export const salesOrderSap = "Sales Oder (SAP)"
export const netValueBySo = "Net Value by SO (ex VAT)"
export const taxAmountBySo = "Tax Amount by SO"
export const totalNetValueBySo = "Total Net Value by SO (inc VAT)"
export const plant = "Plant"
export const shippingPoint = "Shipping Point"
export const salesSupervisor = "Sales Supervisor"
export const simulateSave = "Simulate/Save"
export const submitOrder = "Submit Order"
export const changeOrder = "Change Order"
export const addProduct = "Add Product"

export const reportCreateBy = "โดย"
export const reportCreateDate = "วันที่สร้าง"


export const customerId = "Customer ID"
export const visitId = "Visit ID (Visit)"
export const visitName = "Visit Name"
export const createdOn = "Created On (Visit)"
export const changedOn = "Changed On (Visit)"
export const productOld = "ProductOld"
export const productNameOld = "productNameOld"
export const productNew = "ProductNew"
export const productNameNew = "productNameNew"
export const dispenserReport = "dispenser"
export const nozzleReport = "nozzle"
export const meter_value = "meter_value"
export const dispenserCount = "จำนวนตู้จ่าย"
export const nozzleCount = "จำนวนหัวจ่าย"
export const checkInLatitude = "Check In Latitude"
export const checkInLongitude = "Check In Longitude"
export const employeeResponsibleForVisit = "Employee Responsible For Visit"
export const employeeID = "Employee ID"


export const reportProspectNo = "Prospect No."
export const reportCustFromProspect = "Customer From Prospect"
export const reportPercentRatio = "% Ratio(Convert to Customer)"
export const reportProspectID = "Prospect ID"
export const reportprospectName = "Prospect Name"
export const reportprospectStatus = "Prospect Status"
export const reportSaleGroupID = "Sale Group ID"
export const reportSaleGroupName = "Sale Group Name"
export const reportAddress = "ที่อยู่"
export const reportSubdistrict = "ตำบล"
export const reportDistrict = "อำเภอ"
export const reportProvince = "จังหวัด"
export const reportSaleArea = "Sale Area"
export const reportMeterNagative = "ค่าลบ"
export const reportTotalNagative = "รวมค่าลบ"
export const reportNotTotalNagative = "ไม่รวมค่าลบ"
export const reportDateMeterLastTime = "วันที่จดมิเตอร์ครั้งที่แล้ว (A)"
export const reportDateMaterLast = "วันที่จดมิเตอร์ล่าสุด (B)"
export const reportVisitID1 = "VisitID1"
export const reportVisitID2 = "VisitID2"
export const meter_visit = "meter_visit"
export const meter_summation = "meter_summation"

export const reportAssignProjectName = "ชื่อโครงการ"
export const reportAssignEmpName = "Employee Name"
export const tableProductCode = "Product Code"
export const tableProductCategory = "Product Category"
export const tableDescription = "Description"
export const tableQuantity = "Quantity"
export const tableUnit = "Unit"
export const tableNetPrice1 = "Net Price1 (ex Addition Price)(inc Transfer Price)"
export const tableAdditionalPrice = "Additional Price"
export const tableNetPrice2 = "Net Price2 (inc Additional Price)"
export const tableNetValue = "Net Value"
export const tableTransferPrice = "Transfer Price"
export const tableItemType = "Item Type"
export const quantity = "Quantity"
export const tableStatus = 'สถานะ'
export const tableActive = 'ใช้งาน'
export const tableInActive = 'ไม่ใช้งาน'

export const reportSaleOrderNoSAP = "Sale Order No. (SAP)"
export const reportSaleOrderNoSOM = "Sale Order Ref No. (SOM)"
export const reportSaleOrderStatus = "Status"
export const reportSaleOrderCompany = "Company"
export const reportSaleOrderSaleOrg = "Sale Organization"
export const reportSaleOrderChannel = "Channel"
export const reportSaleOrderDivision = "Division"
export const reportSaleOrderSaleGroup = "Sale Group"
export const reportSaleOrderNetValue = "Total Net Value"
export const reportSaleOrderCreateDate = "วันที่สร้าง"
export const reportSaleOrderCreateBy = "โดย"

export const reportLocStartName = "สถานที่เริ่มต้น"
export const reportLocEndName = "สถานที่สิ้นสุด"
export const reportVisitTimeStart = "เวลาเริ่มต้น"
export const reportVisitTimeStop = "เวลาสิ้นสุด"
export const reportStartCheckinMileNo = "เลขไมล์เริ่มต้น"
export const reportStopCheckinMileNo = "เลขไมล์สิ้นสุด"
export const reportTotalKmInput = "ระยะทาง Total KM (by input)"
export const reportTotalKmSystem = "ระยะทางในระบบ Total KM (by System)"
export const reportLocationName = "สถานที่ (สถานที่เริ่มต้น - สถานที่สิ้นสุด)"
export const reportStatus = "สถานะ"
export const reportContactName = "ชื่อผู้ติดต่อ"
export const reportAddressAndPhone = "ที่อยู่หมายเลขโทรศัพท์"
export const reportVisitDetail = "รายละเอียดการตรวจเยี่ยม"
export const reportTotalKM = "จำนวน (กิโลเมตร)"

export const reportTotalSaleOrder = "Total Sale Order"
export const reportSAP = "SAP"
export const reportSOM = "SOM (with Sale Order No. SAP)"
export const reportPercentSAP = "%SAP"
export const reportPercentSOM = "%SOM"
export const reportSOMBySale = "SOM By Sale"
export const reportBusinessUnit = "Business Unit"

export const reportDDMMYYYY = "วันเดือนปี"
export const reportPlan = "Plan (Prospect/Customer Name)"
export const reportActual = "Actual (Prospect/Customer Name)"
export const changeDateTime = "Change Date/Time"
export const changeTap = "Change Tap"
export const changeBy = "Changed By"
export const saleRepId = "Sale Rep ID"
export const documentFlowProduct = "สินค้า"

export const reportVisitPlan = "Visit Plan"
export const reportSalesTerritoryID = "Sales Territory ID"
export const reportSaleTeritoryName = "Sale Teritory Name"
export const reportCheckInDateTime = "Check-In Date Time"
export const reportCheckOutDateTime = "Check-Out Date Time"
export const reportEmployeeResponsible = "Employee Responsible For Visit (Deprecated)"
export const reportEmployeeID = "Employee ID"
export const reportCustomer = "Customer"
export const reportCustomerID = "Customer ID"
export const reportProductCategoryCode = "Product Category Code"
export const reportProductName = "Product Name"
export const reportProductID = "Product ID"
export const reportQuantity = "Quantity(Unit)"
export const reportUOM = "UOM ตาม SAP"

export const reportSaleTerritory = "Sale Territory"

export const productAndUnitDup = "ข้อมูล Product และ Unit ซ้ำ กรุณาเลือกข้อมูลใหม่"
export const sysGroupStatus = 'สถานะ'
export const activeAndInActive = 'ใช้งาน / ไม่ใช้งาน'
export const notWhithInActive = 'ไม่รวมสถานะไม่ใช้งาน'
export const showQr = 'แสดง QR Code'